### ISSUE TITLE
Wordlists aren't included during installation

### ISSUE THREAD

**Issue by conorsch** [ulif/diceware#1]
The default `wordlist_en.txt` is not included during installation via pip. Steps to reproduce:

```
vagrant@vagrant-ubuntu-trusty-64:~$ sudo aptitude install python-pip
vagrant@vagrant-ubuntu-trusty-64:~$ sudo pip install diceware
```
Then:
```
vagrant@vagrant-ubuntu-trusty-64:~$ diceware
Traceback (most recent call last):
  File "/usr/local/bin/diceware", line 9, in <module>
    load_entry_point('diceware==0.2', 'console_scripts', 'diceware')()
  File "/usr/local/lib/python2.7/dist-packages/diceware.py", line 137, in main
    fd=options.infile
  File "/usr/local/lib/python2.7/dist-packages/diceware.py", line 110, in get_passphrase
    fd = open(get_wordlist_path(lang), 'r')
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/wordlists/wordlist_en.txt'
```
This can be resolved via the `data_files` directive in `setup.py` ([docs](https://docs.python.org/2/distutils/setupscript.html#installing-additional-files)):

```
    data_files=[
        ('wordlists', ['wordlists/wordlist_en.txt']),
        ],
```

Doing so will ensure that `wordlist_en.txt` is accessible by the module. Pull request on its way. Added a few Travis checks as well.

**Comment by ulif** [comment]
Thank you for this important hint! I cannot believe I didn't notice that earlier.

**Comment by ulif** [comment]
Version 0.3 is out. Unfortunately the main problem (wordlists not accessible) still exists. With the data_files directive the wordlists are installed, but in the current directory and not in the package dir.

Will look into this tonight and might start giving 'package_data' a try. Other hints welcome.

**Comment by conorsch** [comment]
You're right that the issue persists even in 0.3. Looks like we need to specify the sys prefix for where modules are installed. The `data_files` declaration is definitely working:

```
vagrant@vagrant-ubuntu-trusty-64:~$ find /usr -name wordlist_en.txt
/usr/local/wordlists/wordlist_en.txt
```
Hard-coding the path in `setup.py` fixes it, but I'd much rather read the prefix dynamically. I'll do some more digging and follow up.

**Comment by ulif** [comment]
Hi Conor,

Thank you very much for all your efforts and research! I really did not expect that much trouble with such a little decision. But I am really glad you found that issue.

I am right now considering two different ways to go:

1) stick with setuptools `data_files` directive, or

2) make the `diceware.py` module a package and put all wordlists therein.

While (1) has the advantage that wordlists would be stored in some 'officially' blessed location where admins etc. can modify them (it would not be hidden inside some egg), it seems to be difficult to determine this location over different systems and platforms. This frightens me a bit.

Futhermore I am pretty sure that installing a new version of diceware would overwrite modified wordlists from any older version. Not sure whether this will really happen, though.

Way (2) would hide away the wordlists a bit (they would be next to the sources) and make them 'hardcoded'. On the other hand it seems to work nicely with `pip`, `python setup.py install`, etc. regardless of platform, virtualenv version and all the other things.  In other words: way (2) looks more stable to me.

Overall I tend to choose way (2) but am open to other suggestions.

-- Uli

**Comment by ulif** [comment]
v0.3.1 seems solve the issue.

Not happy, though. Reliable places for data files, independent from distribution/virtualenv version/etc. would really be nice.

Also regression tests are still lacking.
