### ISSUE TITLE
Finetune new wordlist: shorter name, gpg-sign?

### ISSUE THREAD

**Issue by ulif** [ulif/diceware#14]
With mergin #13 the @heartsucker wordlist is the new default.

There are two minor things left I would love to improve: is there a shorter name available than "en_heartsucker"? Maybe a name that describes it better? Or one that is better memorizable? Like famous hackers or whistleblowers? Just an idea, but we should clarify that before the next release.

Then, @heartsucker, I wonder whether you could (gpg-)sign the new wordlist (just like the other list was signed by Mr. Reinhold. That might simply make the list more trustworthy and people should be able to check whether their local list was modified by someone other than you.

**Comment by heartsucker** [comment]
@ulif Yeah, I can sign it when I get home. Also, feel free to rename it. I just picked my username as the list name because I was feeling uncreative (it's totally not descriptive).
