### ISSUE TITLE
Error for special characters and realdice as random source

### ISSUE THREAD

**Issue by dwcoder** [ulif/diceware#19]
The following command results in an error:

```bash
diceware -n 1 -s 1 -r realdice
# 2
# 2
# 2
# 2
# 2
````

The word that should be chosen in this case is `Cumin`. But it results in an error since I requested special characters, and the word `Cumin` is only 5 characters long. The program isn't setup to choose from a sequence that is shorter than the number of sides on the die.

**Comment by dwcoder** [comment]
This is a great project, by the way. I have forked it, and I will be submitting a pull request shortly, which I hope will fix this issue.

**Comment by ulif** [comment]
Thank you @dwcoder for spotting this bug. And thanks for looking into this!
