### ISSUE TITLE
New EFF Wordlists

### ISSUE THREAD

**Issue by georgevreilly** [ulif/diceware#26]
Joseph Bonneau has published [several new wordlists](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases) under the auspices of the EFF, which offer improved usability over the original list. These lists should be added as alternate sources.

**Comment by ulif** [comment]
Thank you very much @georgevreilly for this hint! I was not aware of EFF creating wordlists and will at least include the long one.

Also the considerations they list are quite interesting and could help to generate better wordlists in general.

**Comment by ulif** [comment]
Being asked, [Joseph Bonneau] (https://www.eff.org/about/staff/joseph-bonneau) from EFF kindly sent a link to EFFs very liberal [copyright rules](https://www.eff.org/copyright). Sorry for wasting your time Joseph!

The list will be part of the upcoming release.
