### ISSUE TITLE
Use Debian-compliant, Machine-Readable Copyright Format

### ISSUE THREAD

**Issue by ulif** [ulif/diceware#28]
I think it would be nice to provide a machine-readable copyright file with `diceware`. It looks like Debian has a policy for that:

  https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/

We have a mix (not to say: mess) of copyright holders and license types due to the different wordlists. To ease additions of further lists, we should implement the Debian copyright policy a.s.a.p., I think.

@drebs As you are more into Debian packaging: could you help with that?

**Comment by anarcat** [comment]
you may want to take a look at https://tracker.debian.org/pkg/decopy for automatically generating that file...

**Comment by ulif** [comment]
Nice one! Thanks a lot, @anarcat ! That was really what I was looking for. The Debian maintainer, @drebs , already worked around the license mess in `diceware`, but this was done more or less manually and it was certainly no fun.

@drebs, do you think `decopy` could help with all our licenses in `diceware`?

**Comment by drebs** [comment]
I've never used decopy. I have used [Debmake](https://tracker.debian.org/pkg/debmake) some times and it generates an initial copyright file for you.

I see one important feature that is to check if all files are covered by the machine-readable copyright file (including globs).

There are tools that might provide suggestions based on analysis of the file tree, but the final list will always need an eye, right? I will ask around and see if there are other suggestions on what could be useful here.

**Comment by anarcat** [comment]
@drebs i'm not sure i follow what you're saying here, but:

 1. yes, you should review the output manually
 2. yes, all files should be covered
 3. yes, there are also other tools, there's an [inventory in the Debian wiki](https://wiki.debian.org/CopyrightReviewTools)

In my experience, decopy works really well and outputs the right machine-readable format...
