### ISSUE TITLE
<<EOF foo EOF support

### ISSUE THREAD

**Issue by dozyh** [ulif/diceware#36]
Is there some way to get this to accept
```
diceware -r realdice <<EOF
1
2
3
4
5
EOF
```

so we don't have to manually type every number?

**Comment by ulif** [comment]
Thanks @dozyh !

I like your proposal. Entering many numbers can really become a bit annoying.
In general something like your sample should be implementable.

Due to other tasks, I probably cannot get really deep into that before next week but just wanted to let you know it is not forgotten and highly appreciated. Thank you!

**Comment by ulif** [comment]
Hi @dozyh 

Sorry for letting you wait. Just checked and in fact you can already use here-documents with `diceware`. You naturally have to know, how many dice rolls are needed beforehand (with default settings five rolls per word requested) but that is all you need.

For instance this works here (in bash):

```
  $ diceware -n 2 -r realdice <<EOF
  > 1
  > 2
  > 3
  ... [numbers 4,5,1,2,3 following]
  > 4
  > 5
  > EOF
  [Lots of output, 'warning', 'please roll 5 dice'...] About About

```
Also echoing input in a pipe works as expected (and so in other shells like `fish`):

```
  $ echo -e '1\n2\n3\n...' | diceware -n 2 -r realdice
  [Lots of output, 'warning', 'please roll 5 dice'...] About About

```
As we speak about input redirection, I think this is really a shell feature and should generally be provided by ones commandline env, i.e. - normally - the shell.

A problem I still see, is the excessive output, being pretty unhelpful when `diceware` is run in scripts. We might introduce a `--quiet` option for this. But that would be a different issue.

As here-docs seem to work fine with `diceware` already, I close this issue.
