### ISSUE TITLE
Wordlists path is hardcoded in API doc

### ISSUE THREAD

**Issue by drebs** [ulif/diceware#39]
The path to wordlist files is hardcoded in the generated sphinx
documentation and because it may differ depending on how the package is
installed this creates different problems:

- the path hardcoded in the online api documentation may differ from
the one in each installation, leading to incorrect information
provided to the user of the api.

- packaging diceware documentation to specific operating systems may
generate unreproducible packages.

One possible solution is to replace the `WORDLISTS_DIR` with a function called `get_wordlists_dir()` and have the path be constructed during execution of the function rather than during module load time.

**Comment by drebs** [comment]
This is a proposal of fix: https://github.com/ulif/diceware/pull/38

**Comment by ulif** [comment]
That's great, thank you @drebs !
Just merged your code. I hope this will help with reproducibility :)
