### ISSUE TITLE
Support Python 3.7

### ISSUE THREAD

**Issue by drebs** [ulif/diceware#54]
Hi!

I am the packager of Diceware for Debian, and because Python 2 is approaching end of life I have already ported the package to Python 3.6. But Debian will soon (2 to 3 weeks, actually) remove support for Python 3.6, so I will need to port the package to Python 3.7.

I have not tried to run Diceware with Python 3.7 yet, but thought I should report here first to check if there's already a movement in that direction or if I should/could help in some way.

Cheers!

**Comment by ulif** [comment]
Hey @drebs 

nice to hear from you :)

Debian drops 3.6 support? Wow! Is there a timeline somewhere, I could keep an eye on in the future?

Regarding py3.7 that should be no problem at all. At least `tox` is happy when running the tests under py3.7, so we should be able to support 3.7 officially very soon.

Cheers

**Comment by drebs** [comment]
Hey, uli!

Regarding timeline, the answer i got was: "there is no timeline. it all depends on how the archive moves and the free time available to those of us who are working on the transition". But they also previously said "probably 2 to 3 weeks".

I can provide a MR for you to review, if that helps. Is it just listing 3.7 in the classifiers and adding a tox environment for 3.7, or is there something else?

**Comment by drebs** [comment]
Uli, thanks a lot for that. Can you please tag a new release so I can update the Debian package accordingly? Thanks a lot!
