### ISSUE TITLE
Remove pkg_resources dependency

### ISSUE THREAD

**Issue by ulif** [ulif/diceware#55]
We use `pkg_resources` for retrieving package version infos. While this is not exactly bad (and even convenient from a developers point of view), it is also the only external dependency we carry with us. It would be nice, to depend on standard lib packages only, which woulg also mean less trouble for maintainers.

**Comment by htgoebel** [comment]
Beside changing the way the version is fetched, this would mean to also eliminate the entry-point mechanism mused to collect the random methods.
