### ISSUE TITLE
Allow non-whitespace to separate numbers in realdice input

### ISSUE THREAD

**Issue by ulif** [ulif/diceware#74]
Current input of dice rolls with the realdice randomness-source expects whitespace characters to separate numbers. With reguiar expressions we could allow also colons, dots, or other (non-digit) chars.

For instance, instead of `1 2 3<CR>2 3 1<CR>` we could accept `1, 2, 3<CR>2-3-1<CR>` and similar input.

This change was brought up by @alanhoyle in #58  based on recent changes from @adinklotz .

**Comment by alanhoyle** [comment]
I've started following  the developer install instructions and will hopefully submit a pull request soon.
