### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by sluedecke** [ulif/diceware#79]
Is it possible to release a new version?

ArchLinux refers to the 0.9.6 version in it's [user package repository](https://aur.archlinux.org/packages/diceware/).  Having a new version would allow for a 'clean' update and the commit log suggests that there are enough changes to do so.

IMHO

**Comment by ulif** [comment]
Your request was really justified. Sorry, the last release really took much too long.
Finally, this issue can be closed - and hopefully stays closed.
Please reopen, if you think, another release should be done.

**Comment by sluedecke** [comment]
Yay, thanks a lot for the new version!
