### ISSUE TITLE
Add infile to options defaults

### ISSUE THREAD

**Issue by qha** [ulif/diceware#84]
Add infile=None to OPTIONS_DEFAULTS in diceware/config.py to permit configuring custom word lists that are not installed in diceware/wordlists.

**Comment by ulif** [comment]
I do not understand. `None` is already the default for the `infile` argument. Could you explain what is not working for you?

**Comment by qha** [comment]
get_config_dict only reads configuration settings that occur in defaults_dict, i take it that's why setting infile in .diceware.ini had no effect for me unlike other settings.

**Comment by ulif** [comment]
Ok, so you want to use a different wordlist by default? The usual way to do this is putting the list into the local wordlist dir (displayed by --help). Is this an option for you?

**Comment by qha** [comment]
Sure, that is an option, i just prefer to keep my own configuration where i can write it without elevating my priveliges.

**Comment by drebs** [comment]
> Sure, that is an option, i just prefer to keep my own configuration where i can write it without elevating my priveliges.

How about if, instead, Diceware included `${XDG_DATA_HOME}/diceware/wordlists` in its search for available wordlists?

**Comment by qha** [comment]
That sounds like it would accomplish everything i wished for when opening this ticket.
